// <auto-generated />
using Contactly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contactly.Migrations
{
    [DbContext(typeof(ContactlyDBContext))]
    partial class ContactlyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contactly.Models.Domain.Contacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactName = "Shruti",
                            Email = "shruti@gmail.com",
                            Favorite = true,
                            Phone = "8617383816"
                        },
                        new
                        {
                            Id = 2,
                            ContactName = "Sujal",
                            Email = "sujal@gmail.com",
                            Favorite = true,
                            Phone = "8617383823"
                        },
                        new
                        {
                            Id = 3,
                            ContactName = "Rohit",
                            Email = "rohit@gmail.com",
                            Favorite = true,
                            Phone = "8617336786"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
